name: Challenge Auth
on: [push]

jobs:
  auth-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::009661764077:role/cicdRole
          aws-region: us-east-1

      - name: Find Website API Endpoint
        run: |
          echo "=== Reading Website JavaScript to find API Endpoint ==="
          aws s3 cp s3://site781fe43f26b9eba3/js/scripts.js - || true
          aws s3 cp s3://site781fe43f26b9eba3/index.html - || true
