name: Challenge Auth Fixed
on: [push]

jobs:
  auth-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::009661764077:role/cicdRole
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: List Resources
        run: |
          aws s3 ls || true
          aws lambda list-functions --region us-east-1 || true
